### PR TITLE
Completed task 5

### PR DESCRIPTION
**Pull request by bukshev**
This task looks already done for my opinion.

### CODE REVIEW

**Comment by Maxim-38RUS-Zabelin** [comment]
А где файл проекта? Я бы хотел собрать и запустить твое приложение.

**Comment by Maxim-38RUS-Zabelin** [comment]
Переданное на проверку приложение не собирается, вот ошибка:

clang: error: no such file or directory: '/Users/user/Downloads/university-ios-assignment-5-9a05eec029143d4611214068893dfe280961566e/UIKitApplication/UIKitApplication/UIKitApplication-Prefix.pch'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

**Comment by bukshev** [comment]
Странно, у меня работает, попробую сейчас перезалить полностью проект, а после приступлю к исправлению ошибок. Возможно, это из-за неправильного расположения файла .xcodeproj
https://pp.vk.me/c622422/v622422179/209c7/O_ZGqWznkY4.jpg

**Comment by Maxim-38RUS-Zabelin** [comment]
Хорошая новость: проект собирается, я смог его запустить. Плохие новости: при сборке проекта компилятор выдает несколько предупреждений (чего быть не должно), первые 2 контроллера отображаются неверно (http://joxi.ru/n2Y8w8yuRvExm6), не работает смена цвета по заданному значению (я пробовал #FFFFFF и 0xFFFFFF), что-то не в порядке с constraints (см. log ниже), приложение падает при попытке попасть на модальный контроллер с информацией об авторе (см. stack-trace ниже).

--- **Constraints** ---
2015-03-08 09:35:47.163 UIKitApplication[1244:58148] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x7fbf2adbd3b0 H:[UIRoundedRectButton:0x7fbf2adbcba0'Next Level'(148)]>",
    "<NSLayoutConstraint:0x7fbf2ae3ca20 UIButton:0x7fbf2adb9280.trailing == UIView:0x7fbf2ae589b0.trailing>",
    "<NSLayoutConstraint:0x7fbf2ae44430 UIButton:0x7fbf2adb9280.centerX == UIRoundedRectButton:0x7fbf2adbcba0'Next Level'.centerX>",
    "<NSLayoutConstraint:0x7fbf2ae58aa0 H:|-(0)-[UIButton:0x7fbf2adb9280]   (Names: '|':UIView:0x7fbf2ae589b0 )>",
    "<NSLayoutConstraint:0x7fbf2ae5aa50 H:|-(86)-[UIRoundedRectButton:0x7fbf2adbcba0'Next Level']   (Names: '|':UIView:0x7fbf2ae589b0 )>",
    "<NSLayoutConstraint:0x7fbf2add5280 'UIView-Encapsulated-Layout-Width' H:[UIView:0x7fbf2ae589b0(568)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fbf2adbd3b0 H:[UIRoundedRectButton:0x7fbf2adbcba0'Next Level'(148)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-03-08 09:35:47.164 UIKitApplication[1244:58148] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x7fbf2adbe0c0 H:[UISlider:0x7fbf2adbda50(114)]>",
    "<NSLayoutConstraint:0x7fbf2af1a560 H:[UITextField:0x7fbf2adbec30(97)]>",
    "<NSLayoutConstraint:0x7fbf2ae3b1f0 H:|-(81)-[UISlider:0x7fbf2adbda50]   (Names: '|':UIView:0x7fbf2ae589b0 )>",
    "<NSLayoutConstraint:0x7fbf2ae5ab90 H:[UITextField:0x7fbf2adbec30]-(NSSpace(20))-|   (Names: '|':UIView:0x7fbf2ae589b0 )>",
    "<NSLayoutConstraint:0x7fbf2add5280 'UIView-Encapsulated-Layout-Width' H:[UIView:0x7fbf2ae589b0(568)]>",
    "<NSLayoutConstraint:0x7fbf2ae5abe0 H:[UISlider:0x7fbf2adbda50]-(NSSpace(8))-[UITextField:0x7fbf2adbec30]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fbf2adbe0c0 H:[UISlider:0x7fbf2adbda50(114)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

--- **Crash** ---
2015-03-08 09:44:53.225 UIKitApplication[1244:58148] -[ViewController setDescription:]: unrecognized selector sent to instance 0x7fbf2d123f00
2015-03-08 09:44:53.230 UIKitApplication[1244:58148] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ViewController setDescription:]: unrecognized selector sent to instance 0x7fbf2d123f00'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010847bf35 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x0000000107115bb7 objc_exception_throw + 45
    2   CoreFoundation                      0x000000010848304d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
    3   CoreFoundation                      0x00000001083db27c ___forwarding_** + 988
    4   CoreFoundation                      0x00000001083dae18 _CF_forwarding_prep_0 + 120
    5   UIKitApplication                    0x00000001056d38ad -[ViewController viewDidLoad] + 861
    6   UIKit                               0x00000001058a0a90 -[UIViewController loadViewIfRequired] + 738
    7   UIKit                               0x00000001058a0c8e -[UIViewController view] + 27
    8   UIKit                               0x0000000105e4241e -[_UIFullscreenPresentationController _setPresentedViewController:] + 65
    9   UIKit                               0x000000010587c429 -[UIPresentationController initWithPresentedViewController:presentingViewController:] + 105
    10  UIKit                               0x00000001058aca41 -[UIViewController _presentViewController:withAnimationController:completion:] + 1746
    11  UIKit                               0x00000001058aed81 __62-[UIViewController presentViewController:animated:completion:]_block_invoke + 132
    12  UIKit                               0x00000001058aeca5 -[UIViewController presentViewController:animated:completion:] + 229
    13  UIKitApplication                    0x00000001056d748b -[InformationViewController fullInfoButtonTap:] + 171
    14  UIKit                               0x000000010577c8be -[UIApplication sendAction:to:from:forEvent:] + 75
    15  UIKit                               0x0000000105883410 -[UIControl _sendActionsForEvents:withEvent:] + 467
    16  UIKit                               0x00000001058827df -[UIControl touchesEnded:withEvent:] + 522
    17  UIKit                               0x00000001057c2308 -[UIWindow _sendTouchesForEvent:] + 735
    18  UIKit                               0x00000001057c2c33 -[UIWindow sendEvent:] + 683
    19  UIKit                               0x000000010578f9b1 -[UIApplication sendEvent:] + 246
    20  UIKit                               0x000000010579ca7d _UIApplicationHandleEventFromQueueEvent + 17370
    21  UIKit                               0x0000000105778103 _UIApplicationHandleEventQueue + 1961
    22  CoreFoundation                      0x00000001083b1551 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    23  CoreFoundation                      0x00000001083a741d __CFRunLoopDoSources0 + 269
    24  CoreFoundation                      0x00000001083a6a54 __CFRunLoopRun + 868
    25  CoreFoundation                      0x00000001083a6486 CFRunLoopRunSpecific + 470
    26  GraphicsServices                    0x00000001083199f0 GSEventRunModal + 161
    27  UIKit                               0x000000010577b420 UIApplicationMain + 1282
    28  UIKitApplication                    0x00000001056d2cf3 main + 115
    29  libdyld.dylib                       0x000000010c2b1145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by Maxim-38RUS-Zabelin** [comment]
Иван, в целом по коду получилось весьма неплохо, но вот работоспособность приложения оставляет желать лучшего. Оценку за работу я уже выставил, сейчас закрою pull запрос, однако,  рекомендую тебе провести работу над ошибками. Ее можно оформить новым pull запросом, - я обязательно проверю и дам свой комментарий.

**Pull request closed without merging**
